"""empty message

Revision ID: 20c251ae5cd9
Revises: 449f46a11c94
Create Date: 2020-05-30 00:35:27.616257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c251ae5cd9'
down_revision = '449f46a11c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('last_modify', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_article_last_modify'), 'article', ['last_modify'], unique=False)
    op.create_index(op.f('ix_article_time'), 'article', ['time'], unique=False)
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_time'), 'comment', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_time'), table_name='comment')
    op.drop_column('comment', 'time')
    op.drop_index(op.f('ix_article_time'), table_name='article')
    op.drop_index(op.f('ix_article_last_modify'), table_name='article')
    op.drop_column('article', 'time')
    op.drop_column('article', 'last_modify')
    # ### end Alembic commands ###
