"""empty message

Revision ID: 36affa8886ec
Revises: 20c251ae5cd9
Create Date: 2020-05-30 23:26:10.304050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36affa8886ec'
down_revision = '20c251ae5cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('article', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.add_column('comment', sa.Column('is_show', sa.Boolean(), nullable=True))
    op.alter_column('comment', 'article_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('comment', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('role', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('comment', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('comment', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('comment', 'article_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('comment', 'is_show')
    op.alter_column('article', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('article', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
