"""empty message

Revision ID: 3ca78846e665
Revises: 91eac8c57eec
Create Date: 2020-05-28 00:44:40.337744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ca78846e665'
down_revision = '91eac8c57eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.create_table('users',
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('confirm', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('info', mysql.TEXT(), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('protrait', mysql.VARCHAR(length=64), nullable=True),
    sa.CheckConstraint('(`confirm` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('username'),
    mysql_default_charset='gbk',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
