"""empty message

Revision ID: 449f46a11c94
Revises: 3ca78846e665
Create Date: 2020-05-29 21:22:24.608164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449f46a11c94'
down_revision = '3ca78846e665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=32), nullable=True))
    op.add_column('comment', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'body')
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
