"""empty message

Revision ID: 91eac8c57eec
Revises: b142478e4777
Create Date: 2020-05-27 19:40:52.291046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eac8c57eec'
down_revision = 'b142478e4777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('protrait', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'protrait')
    # ### end Alembic commands ###
